import type { IconSet } from '@iconify/tools'
import type { IconifyJSON } from '@iconify/types'
import type { ResolvedIconctlConfig } from './config'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { exportJSONPackage, exportToDirectory, writeJSONFile } from '@iconify/tools'
import { dirname, join } from 'pathe'

export interface ExportResult {
  files: string[]
  json: IconifyJSON
}

async function writeTextFile(file: string, contents: string) {
  await mkdir(dirname(file), { recursive: true })
  await writeFile(file, contents, 'utf8')
}

export function generateIconNameTypes(prefix: string, names: string[]): string {
  const union = names.length
    ? names.map(name => `'${name}'`).join(' | ')
    : 'never'
  return `export const ICONIFY_PREFIX = '${prefix}' as const\nexport type IconName = ${union}\n`
}

export async function readPreviousIconJson(file: string): Promise<IconifyJSON | undefined> {
  try {
    return JSON.parse(await readFile(file, 'utf8')) as IconifyJSON
  }
  catch {
    return undefined
  }
}

export async function exportOutputs(
  iconSet: IconSet,
  config: ResolvedIconctlConfig,
  options: { cwd: string, dryRun?: boolean } = { cwd: process.cwd() },
): Promise<ExportResult> {
  const files: string[] = []
  const json = iconSet.export()
  const resolve = (file: string) => file.startsWith('/') ? file : join(options.cwd, file)

  if (!options.dryRun) {
    const jsonFile = resolve(config.output.json)
    await mkdir(dirname(jsonFile), { recursive: true })
    await writeJSONFile(jsonFile, json)
    files.push(jsonFile)

    if (config.output.svg) {
      const svgDir = resolve(config.output.svg)
      await exportToDirectory(iconSet, { target: svgDir })
      files.push(svgDir)
    }

    if (config.output.jsonPackage) {
      const pkg = config.output.jsonPackage
      const dir = resolve(pkg.dir)
      let existing: Record<string, unknown> = {}
      if (pkg.clean === false) {
        try {
          existing = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8')) as Record<string, unknown>
        }
        catch {
          existing = {}
        }
      }
      await exportJSONPackage(iconSet, {
        target: dir,
        cleanup: pkg.clean !== false,
        package: {
          name: pkg.name ?? `@iconify-json/${config.prefix}`,
          description: `Iconify JSON generated by iconctl`,
          ...(typeof existing['version'] === 'string' ? { version: existing['version'] } : {}),
          ...pkg.package,
        },
        customisePackage: (contents) => {
          if (pkg.clean !== false) {
            return
          }
          for (const key of ['private', 'scripts', 'files', 'devDependencies', 'author', 'license', 'repository', 'bugs', 'keywords']) {
            if (existing[key] != null && contents[key] == null) {
              contents[key] = existing[key]
            }
          }
        },
      })
      files.push(dir)
    }

    if (config.output.types) {
      const names = Object.keys(json.icons).sort()
      const typesFile = resolve(config.output.types)
      await writeTextFile(typesFile, generateIconNameTypes(config.prefix, names))
      files.push(typesFile)
    }
  }

  return { files, json }
}
