import type { IconSet } from '@iconify/tools'
import type { IconifyJSON } from '@iconify/types'
import type { ResolvedIconctlConfig } from './config'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { exportJSONPackage, writeJSONFile } from '@iconify/tools'
import { dirname, isAbsolute, join, relative, resolve as resolvePath } from 'pathe'
import { checkpoint } from './abort'
import { IconctlError } from './errors'
import { OutputTransaction } from './output-transaction'

export interface ExportResult {
  files: string[]
  json: IconifyJSON
}

async function writeTextFile(file: string, contents: string) {
  await mkdir(dirname(file), { recursive: true })
  await writeFile(file, contents, 'utf8')
}

export function generateIconNameTypes(prefix: string, names: string[]): string {
  const union = names.length
    ? names.map(name => `'${name}'`).join(' | ')
    : 'never'
  return `export const ICONIFY_PREFIX = '${prefix}' as const\nexport type IconName = ${union}\n`
}

export async function readPreviousIconJson(file: string): Promise<IconifyJSON | undefined> {
  try {
    return JSON.parse(await readFile(file, 'utf8')) as IconifyJSON
  }
  catch {
    return undefined
  }
}

export async function generateOutputs(
  iconSet: IconSet,
  config: ResolvedIconctlConfig,
  options: { cwd: string, dryRun?: boolean, signal?: AbortSignal } = { cwd: process.cwd() },
): Promise<ExportResult> {
  const files: string[] = []
  const json = iconSet.export()
  const resolve = (file: string) => file.startsWith('/') ? file : join(options.cwd, file)

  if (!options.dryRun) {
    await checkpoint(options.signal)
    if (config.output.jsonPackage) {
      const pkg = config.output.jsonPackage
      const dir = resolve(pkg.dir)
      let existing: Record<string, unknown> = {}
      if (pkg.clean === false) {
        try {
          existing = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8')) as Record<string, unknown>
        }
        catch {
          existing = {}
        }
      }
      await exportJSONPackage(iconSet, {
        target: dir,
        cleanup: pkg.clean !== false,
        package: {
          name: pkg.name ?? `@iconify-json/${config.prefix}`,
          description: `Iconify JSON generated by iconctl`,
          ...(typeof existing['version'] === 'string' ? { version: existing['version'] } : {}),
          ...pkg.package,
        },
        customisePackage: (contents) => {
          if (pkg.clean !== false) {
            return
          }
          for (const key of ['private', 'scripts', 'files', 'devDependencies', 'author', 'license', 'repository', 'bugs', 'keywords']) {
            if (existing[key] != null && contents[key] == null) {
              contents[key] = existing[key]
            }
          }
        },
      })
      files.push(dir)
    }

    await checkpoint(options.signal)
    const jsonFile = resolve(config.output.json)
    await mkdir(dirname(jsonFile), { recursive: true })
    await writeJSONFile(jsonFile, json)
    files.push(jsonFile)

    if (config.output.svg) {
      const svgDir = resolve(config.output.svg)
      await mkdir(svgDir, { recursive: true })
      await iconSet.forEach(async (name) => {
        await checkpoint(options.signal)
        const svg = iconSet.toString(name, { width: 'auto', height: 'auto' })
        if (svg) {
          const target = join(svgDir, `${name}.svg`)
          const path = relative(svgDir, target)
          if (path === '..' || path.startsWith('../') || isAbsolute(path)) {
            throw new IconctlError(`SVG name escapes the output directory: ${name}`)
          }
          await writeTextFile(target, svg)
        }
      })
      files.push(svgDir)
    }

    await checkpoint(options.signal)
    if (config.output.types) {
      const names = Object.keys(json.icons).sort()
      const typesFile = resolve(config.output.types)
      await writeTextFile(typesFile, generateIconNameTypes(config.prefix, names))
      files.push(typesFile)
    }
  }

  const order = [config.output.json, config.output.svg, config.output.jsonPackage?.dir, config.output.types]
    .flatMap(file => file ? [resolve(file)] : [])
  files.sort((a, b) => order.indexOf(a) - order.indexOf(b))
  return { files, json }
}

export function outputTargets(config: ResolvedIconctlConfig, cwd: string): { path: string, directory?: boolean }[] {
  const output = config.output
  return [
    { path: resolvePath(cwd, output.json) },
    ...(output.svg ? [{ path: resolvePath(cwd, output.svg), directory: true }] : []),
    ...(output.jsonPackage ? [{ path: resolvePath(cwd, output.jsonPackage.dir), directory: true }] : []),
    ...[output.types, output.preview, output.changelog].flatMap(file => file ? [{ path: resolvePath(cwd, file) }] : []),
  ]
}

export function stagedConfig(config: ResolvedIconctlConfig, cwd: string, transaction: OutputTransaction): ResolvedIconctlConfig {
  const path = (file: string) => transaction.path(resolvePath(cwd, file))
  const output = config.output
  return {
    ...config,
    output: {
      json: path(output.json),
      ...(output.svg ? { svg: path(output.svg) } : {}),
      ...(output.jsonPackage ? { jsonPackage: { ...output.jsonPackage, dir: path(output.jsonPackage.dir) } } : {}),
      ...(output.types ? { types: path(output.types) } : {}),
      ...(output.preview ? { preview: path(output.preview) } : {}),
      ...(output.changelog ? { changelog: path(output.changelog) } : {}),
    },
  }
}

export async function exportOutputs(
  iconSet: IconSet,
  config: ResolvedIconctlConfig,
  options: { cwd: string, dryRun?: boolean, signal?: AbortSignal } = { cwd: process.cwd() },
): Promise<ExportResult> {
  await checkpoint(options.signal)
  if (options.dryRun) {
    return { files: [], json: iconSet.export() }
  }
  // Preview and changelog remain sync() responsibilities.
  const { preview: _preview, changelog: _changelog, ...output } = config.output
  const exportConfig = { ...config, output }
  const targets = outputTargets(exportConfig, options.cwd)
  const transaction = await OutputTransaction.create(targets, options.signal)
  try {
    const generatedConfig = stagedConfig(exportConfig, options.cwd, transaction)
    const result = await generateOutputs(iconSet, generatedConfig, options)
    await transaction.commit(options.signal)
    return { json: result.json, files: targets.map(target => target.path) }
  }
  finally {
    await transaction.dispose()
  }
}
