export { runCli } from './program.ts'
export {
  check,
  compareIconSets,
  defineConfig,
  diffIconSets,
  IconctlAbortError,
  IconctlCheckError,
  IconctlError,
  IconctlSyncError,
  loadConfig,
  parseFigmaFileKey,
  renderDiffHtml,
  renderPreviewHtml,
  resolveConfig,
  sync,
  writeDiffHtml,
  writePreviewHtml,
} from '@iconctl/core'
export type {
  CheckInputOptions,
  CheckIssue,
  CheckOptions,
  CheckReport,
  CheckResult,
  CheckValidation,
  IconComparisonEntry,
  IconctlConfig,
  IconDiff,
  IconSetComparison,
  SourceConfig,
  SyncIssue,
  SyncOptions,
  SyncResult,
  WriteDiffHtmlOptions,
  WritePreviewHtmlOptions,
} from '@iconctl/core'
