import type { Download, Page, TestInfo } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { runInNewContext } from 'node:vm'
import { test as base, expect } from '@playwright/test'

interface Message {
  type: string
  scanId?: number
  requestId?: number
  format?: string
  html?: string
  json?: string
  [key: string]: unknown
}
interface CapturedReport {
  schemaVersion: number
  page: { name: string }
  rules: { name: string }
  items: { id: string, name: string, iconName: string | null, skipped: boolean, issues: string[] }[]
}
interface Node { id: string, name: string, type: string, width?: number, height?: number, children?: Node[] }
interface Resource { type: string, url?: string }
const hostile = '</script><img data-injected="html-report" src="https://invalid.example/leak" onerror="alert(1)"> & "设计"'
const longName = `${'设计系统'.repeat(42)} ${hostile}`
const pageName = `Icons ${hostile}`
const projectName = `Brand ${hostile}`

// Execute the built Figma host entry with a small sandbox API adapter. HTML is
// generated by the real immutable PreflightReport, never by a fixture renderer.
async function host() {
  const page: Node = { id: `page:${hostile}`, name: pageName, type: 'PAGE', children: [
    { id: '1:1', name: 'Arrow', type: 'COMPONENT', width: 16, height: 24 },
    { id: `1:${hostile}`, name: longName, type: 'COMPONENT', width: 48, height: 24 },
    { id: '1:3', name: `Draft<& ${hostile}`, type: 'COMPONENT', width: 16, height: 24 },
    { id: '1:4', name: 'Wide', type: 'COMPONENT', width: 48, height: 32 },
  ] }
  const stored = new Map<string, unknown>([
    ['iconctl-console-device', { origin: 'https://iconctl.icebreaker.top', deviceId: 'html-device-secret', projectId: 'project', token: 'html-device-token' }],
    ['iconctl-settings', { repo: 'secret/repo', token: 'html-github-token', eventType: 'html-private-event' }],
  ])
  const messages: Message[] = []
  const handlers = new Map<string, () => void>()
  const figma = {
    currentPage: page,
    showUI: () => {},
    ui: { postMessage: (message: Message) => messages.push(structuredClone(message)), onmessage: undefined as ((message: Message) => Promise<void>) | undefined },
    clientStorage: {
      getAsync: async (key: string) => stored.get(key),
      setAsync: async (key: string, value: unknown) => { stored.set(key, value) },
      deleteAsync: async (key: string) => { stored.delete(key) },
    },
    on: (name: string, callback: () => void) => handlers.set(name, callback),
    getNodeByIdAsync: async () => null,
    viewport: { scrollAndZoomIntoView: () => {} },
  }
  let context = { projectId: 'project', name: projectName, revision: 9, validate: { width: 16, height: 24, name: '^arrow$', skipPrefix: ['Draft<&'] }, namingMode: 'default' }
  const requests: string[] = []
  runInNewContext(await readFile('../../packages/figma-plugin/dist/code.js', 'utf8'), {
    figma,
    __html__: '',
    URL,
    Response,
    setTimeout,
    clearTimeout,
    fetch: async (input: string) => {
      requests.push(input)
      expect(input).toBe('https://iconctl.icebreaker.top/api/plugin/devices/html-device-secret/context')
      return Response.json(context)
    },
  })
  const send = async (message: Message) => figma.ui.onmessage!(message)
  await send({ type: 'load-settings' })
  await send({ type: 'console-status' })
  const scan = () => messages.filter(message => message.type === 'preflight').at(-1)!
  const report = async (request: Message) => {
    const before = messages.length
    await send(request)
    const result = messages.slice(before).find(message => message.type === 'preflight-report')
    expect(result).toBeDefined()
    return result!
  }
  return { page, requests, scan, report, send, close: () => handlers.get('close')!(), context: async (server: boolean) => {
    context = { ...context, namingMode: server ? 'server' : 'default' }
    await send({ type: 'console-status' })
  } }
}

const instrumentation = `<script>
  parent.__htmlResources = [];
  const record = (type, url) => parent.__htmlResources.push({ type, url });
  const create = URL.createObjectURL.bind(URL);
  const revoke = URL.revokeObjectURL.bind(URL);
  const click = HTMLAnchorElement.prototype.click;
  const NativeBlob = Blob;
  window.Blob = new Proxy(NativeBlob, { construct(target, args) {
    if (window.__htmlFailure === 'blob') throw new Error('fixture Blob failure');
    return Reflect.construct(target, args);
  }});
  URL.createObjectURL = (blob) => {
    if (window.__htmlFailure === 'url') throw new Error('fixture URL failure');
    const url = create(blob); record('create', url); return url;
  };
  URL.revokeObjectURL = (url) => { record('revoke', url); return revoke(url); };
  HTMLAnchorElement.prototype.click = function() {
    if (this.download) {
      record('click', this.href);
      if (window.__htmlFailure === 'click') throw new Error('fixture click failure');
    }
    return click.call(this);
  };
</script>`

async function plugin(page: Page) {
  const actualHost = await host()
  const messages: Message[] = []
  await page.exposeFunction('recordHtmlMessage', (message: Message) => messages.push(message))
  await page.setContent('<iframe title="Figma plugin" style="width:420px;height:560px"></iframe>')
  const html = (await readFile('../../packages/figma-plugin/dist/ui.html', 'utf8')).replace('<head>', `<head>${instrumentation}`)
  await page.evaluate((html) => {
    const frame = document.querySelector('iframe')!
    window.addEventListener('message', (event) => {
      if (event.source === frame.contentWindow && event.data.pluginMessage) {
        void (window as unknown as { recordHtmlMessage: (message: Message) => Promise<void> }).recordHtmlMessage(event.data.pluginMessage)
      }
    })
    frame.srcdoc = html
  }, html)
  const ui = page.frameLocator('iframe')
  await expect.poll(() => messages.some(message => message.type === 'rescan')).toBe(true)
  const send = (message: Message) => page.evaluate(message => new Promise<void>((resolve) => {
    const frame = document.querySelector('iframe')!.contentWindow!
    frame.addEventListener('message', () => resolve(), { once: true })
    frame.postMessage({ pluginMessage: message }, '*')
  }), message)
  await send(actualHost.scan())
  const requests = () => messages.filter(message => message.type === 'export-report')
  const button = (format = 'html') => ui.getByRole('button', { name: `Export ${format.toUpperCase()} report`, exact: true })
  const exported = async (format = 'html') => {
    const before = requests().length
    await button(format).click()
    await expect.poll(() => requests().length).toBe(before + 1)
    return requests().at(-1)!
  }
  const resources = () => page.evaluate(() => (window as unknown as { __htmlResources: Resource[] }).__htmlResources)
  const failure = (value: string) => ui.locator('body').evaluate((_element, value) => {
    (window as unknown as { __htmlFailure: string }).__htmlFailure = value
  }, value)
  return { ui, actualHost, send, button, exported, requests, resources, failure, messages }
}
type Plugin = Awaited<ReturnType<typeof plugin>>
const test = base.extend<{ plugin: Plugin }>({
  plugin: async ({ page }, use) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    const instance = await plugin(page)
    try {
      await use(instance)
      expect(errors).toEqual([])
    }
    finally {
      instance.actualHost.close()
    }
  },
})
async function save(download: Download, info: TestInfo, name: string) {
  expect(await download.failure()).toBeNull()
  const path = info.outputPath(name)
  await download.saveAs(path)
  return { path, text: await readFile(path, 'utf8') }
}
async function released(plugin: Plugin) {
  await expect.poll(async () => {
    const events = await plugin.resources()
    return events.filter(item => item.type === 'create').every(item => events.some(other => other.type === 'revoke' && item.url === other.url))
  }).toBe(true)
  await expect(plugin.ui.locator('a[download]')).toHaveCount(0)
}

test('downloads actual captured HTML and JSON, opens the complete hostile report offline, and prints it without executing content', async ({ page, context, plugin }, info) => {
  const network: string[] = []
  page.on('request', request => network.push(request.url()))
  await plugin.ui.getByLabel('Search preflight', { exact: true }).fill('no matching component')
  await plugin.ui.getByLabel('Problems only', { exact: true }).check()
  await expect(plugin.ui.locator('#list > li')).toHaveCount(0)
  const first = await plugin.exported()
  expect(first.format).toBe('html')
  await expect(plugin.button()).toBeDisabled()
  await expect(plugin.button('json')).toBeDisabled()
  await plugin.button('json').evaluate(element => (element as HTMLButtonElement).click())
  expect(plugin.requests()).toHaveLength(1)
  const captured = await plugin.actualHost.report(first)
  // Changing the live host page after capture cannot alter either format.
  plugin.actualHost.page.name = 'Renamed after capture'
  plugin.actualHost.page.children![0]!.name = 'Mutated after capture'
  const download = page.waitForEvent('download')
  await plugin.send(captured)
  const file = await download
  expect(file.suggestedFilename()).toBe(`iconctl-preflight-${first.scanId}.html`)
  const html = await save(file, info, 'actual-host-report.html')
  expect(html.text).toBe(`${captured.html}\n`)
  expect(html.text).not.toMatch(/html-device-secret|html-device-token|html-github-token|html-private-event|secret\/repo|Renamed after capture|Mutated after capture/)
  await released(plugin)
  const jsonRequest = await plugin.exported('json')
  const jsonDownload = page.waitForEvent('download')
  await plugin.send(await plugin.actualHost.report(jsonRequest))
  const json = await save(await jsonDownload, info, 'same-scan-report.json')
  const report = JSON.parse(json.text) as CapturedReport
  expect(report).toMatchObject({ schemaVersion: 1, page: { name: pageName }, project: { name: projectName, revision: 9 }, summary: { total: 4, checked: 3, skipped: 1, withIssues: 2, issueCount: 4 } })
  await released(plugin)
  const prior = await plugin.resources()
  await plugin.send(captured)
  expect(await plugin.resources()).toEqual(prior)
  expect(network).toEqual([])
  expect(plugin.messages.filter(message => ['console-sync', 'dispatch', 'upload', 'save-settings'].includes(message.type))).toEqual([])

  const offline = await context.newPage()
  const external: string[] = []
  const errors: string[] = []
  offline.on('pageerror', error => errors.push(error.message))
  offline.on('console', (message) => {
    if (message.type() === 'error') {
      errors.push(message.text())
    }
  })
  offline.on('request', (request) => {
    if (!request.url().startsWith('file:')) {
      external.push(request.url())
    }
  })
  await offline.route('https://**/*', route => route.abort())
  try {
    await offline.goto(pathToFileURL(html.path).href)
    await expect(offline.getByRole('heading', { name: 'Preflight report', exact: true })).toBeVisible()
    await expect(offline.locator('article')).toHaveCount(report.items.length)
    await expect(offline.locator('article h3')).toHaveText(report.items.map(item => item.name))
    await expect(offline.locator('.page-name')).toHaveText(report.page.name)
    await expect(offline).toHaveTitle(`${pageName} · iconctl preflight`)
    await expect(offline.locator('[data-injected], img, svg, script, iframe, link, form, a')).toHaveCount(0)
    await expect(offline.locator('meta[http-equiv="Content-Security-Policy"]')).toHaveAttribute('content', 'default-src \'none\'; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'')
    const metadata = offline.getByRole('region', { name: 'Applied rules and scan', exact: true })
    await expect(metadata).toContainText(projectName)
    await expect(metadata).toContainText(report.rules.name)
    await expect(metadata).toContainText('Draft<&')
    for (const [index, item] of report.items.entries()) {
      const article = offline.locator('article').nth(index)
      await expect(article).toContainText(item.id)
      await expect(article).toContainText(item.iconName ?? '(none)')
      await expect(article.locator('.issues li')).toHaveText(item.issues)
      await expect(article).toContainText(item.skipped ? 'Skipped draft' : item.issues.length ? 'Needs fixes' : 'Passed local checks')
    }
    expect(await offline.evaluate((literal) => {
      window.getSelection()?.removeAllRanges()
      return (window as unknown as { find: (text: string) => boolean }).find(literal)
    }, 'Wide')).toBe(true)
    expect(await offline.evaluate(() => window.getSelection()?.toString())).toBe('Wide')
    await offline.evaluate(() => window.getSelection()?.removeAllRanges())
    await offline.screenshot({ path: info.outputPath('html-report-desktop.png'), fullPage: true })
    await offline.setViewportSize({ width: 390, height: 844 })
    expect(await offline.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await offline.screenshot({ path: info.outputPath('html-report-mobile.png'), fullPage: true })
    await offline.emulateMedia({ media: 'print' })
    await offline.pdf({ path: info.outputPath('html-report-print.pdf'), format: 'A4', printBackground: true })
    expect(external).toEqual([])
    expect(errors).toEqual([])
  }
  finally {
    await offline.close()
  }
})

test('keeps one export owner across formats and rejects wrong formats, replay, scan IDs and request IDs', async ({ page, plugin }, info) => {
  const first = await plugin.exported()
  const payload = await plugin.actualHost.report(first)
  const pending = await plugin.ui.locator('#report-status').textContent()
  await plugin.send({ ...payload, format: 'json', json: '{}' })
  await plugin.send({ ...payload, format: undefined })
  await plugin.send({ ...payload, scanId: first.scanId! + 1 })
  await plugin.send({ ...payload, requestId: first.requestId! + 1 })
  await plugin.send({ type: 'preflight-report', scanId: first.scanId, requestId: first.requestId, error: true, text: 'Wrong legacy JSON error' })
  expect(await plugin.resources()).toEqual([])
  await expect(plugin.ui.locator('#report-status')).toHaveText(pending!)
  await expect(plugin.button('json')).toBeDisabled()
  const download = page.waitForEvent('download')
  await plugin.send(payload)
  await save(await download, info, 'format-owner.html')
  await released(plugin)
  const json = await plugin.exported('json')
  await plugin.send({ ...payload, requestId: json.requestId })
  await expect(plugin.button()).toBeDisabled()
  const before = await plugin.resources()
  const jsonDownload = page.waitForEvent('download')
  const legacy = await plugin.actualHost.report(json)
  expect(legacy.format).toBeUndefined()
  await plugin.send(legacy)
  expect(JSON.parse((await save(await jsonDownload, info, 'legacy-json.json')).text).schemaVersion).toBe(1)
  await released(plugin)
  await plugin.send(payload)
  expect((await plugin.resources()).filter(event => event.type === 'create')).toHaveLength(before.filter(event => event.type === 'create').length + 1)
})

for (const trigger of ['rescan', 'page', 'mode', 'disconnect', 'new-scan'] as const) {
  test(`isolates pending HTML after ${trigger} and recovers only with a valid new scan`, async ({ plugin }) => {
    const request = await plugin.exported()
    const payload = await plugin.actualHost.report(request)
    if (trigger === 'rescan') {
      await plugin.ui.getByRole('button', { name: 'Rescan', exact: true }).click()
    }
    else if (trigger === 'page') {
      await plugin.send({ type: 'navigation-invalidated', scanId: request.scanId! + 1, text: 'Page changed. Rescan the new page.' })
    }
    else if (trigger === 'mode') {
      await plugin.ui.getByLabel('Connection mode').selectOption('github')
    }
    else if (trigger === 'disconnect') {
      await plugin.ui.getByRole('button', { name: 'Disconnect', exact: true }).click()
    }
    else {
      await plugin.actualHost.send({ type: 'rescan' })
      await plugin.send(plugin.actualHost.scan())
    }
    const feedback = await plugin.ui.locator('#report-status').textContent()
    await plugin.send(payload)
    expect(await plugin.resources()).toEqual([])
    await expect(plugin.ui.locator('#report-status')).toHaveText(feedback!)
    if (trigger !== 'new-scan') {
      await expect(plugin.button()).toBeDisabled()
      await expect(plugin.button('json')).toBeDisabled()
      await plugin.actualHost.send({ type: 'rescan', mode: trigger === 'mode' ? 'github' : 'console' })
      await plugin.send(plugin.actualHost.scan())
    }
    const current = await plugin.exported()
    await plugin.send({ type: 'preflight-report', format: 'html', scanId: current.scanId, requestId: current.requestId, error: true, rescan: true, text: 'This scan is no longer available. Rescan the page before exporting.' })
    await expect(plugin.button()).toBeDisabled()
    await expect(plugin.button('json')).toBeDisabled()
    expect(await plugin.resources()).toEqual([])
  })
}

for (const failure of ['blob', 'url', 'click'] as const) {
  test(`releases a failed HTML ${failure} download and retries with a fresh request`, async ({ page, plugin }, info) => {
    await plugin.failure(failure)
    const failed = await plugin.exported()
    await plugin.send(await plugin.actualHost.report(failed))
    await expect(plugin.ui.locator('#report-status')).toHaveText('Could not download the report. Try exporting again.')
    await expect(plugin.button()).toBeEnabled()
    await expect(plugin.button('json')).toBeEnabled()
    await released(plugin)
    await plugin.failure('')
    const retry = await plugin.exported()
    expect(retry.requestId).toBeGreaterThan(failed.requestId!)
    const download = page.waitForEvent('download')
    await plugin.send(await plugin.actualHost.report(retry))
    await save(await download, info, 'retried-report.html')
    await released(plugin)
    expect((await plugin.resources()).filter(event => event.type === 'create')).toHaveLength(failure === 'click' ? 2 : 1)
  })
}

test('exports an empty scan with provisional rules by keyboard at 420 by 560', async ({ page, plugin }, info) => {
  plugin.actualHost.page.children = []
  await plugin.actualHost.context(true)
  await plugin.send(plugin.actualHost.scan())
  await expect(plugin.button()).toBeEnabled()
  await expect(plugin.ui.getByRole('button', { name: 'Sync to console', exact: true })).toBeDisabled()
  await plugin.button('json').focus()
  await page.keyboard.press('Tab')
  await expect(plugin.button()).toBeFocused()
  await page.keyboard.press('Enter')
  await expect.poll(() => plugin.requests().length).toBe(1)
  const request = plugin.requests()[0]!
  const download = page.waitForEvent('download')
  await plugin.send(await plugin.actualHost.report(request))
  const result = await save(await download, info, 'empty-server-report.html')
  expect(result.text).toContain('No components were found in this scan.')
  expect(result.text).toContain('Names are provisional until custom server naming runs.')
  await expect(plugin.ui.locator('#report-status')).toContainText('Names are provisional until server naming runs.')
  await expect(plugin.ui.locator('#report-status')).toHaveAttribute('aria-live', 'polite')
  await released(plugin)
  expect(await plugin.ui.locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await plugin.button().scrollIntoViewIfNeeded()
  await expect(plugin.button()).toBeInViewport()
  await expect(plugin.button('json')).toBeInViewport()
  await page.locator('iframe').screenshot({ path: info.outputPath('html-export-keyboard.png') })
})
